### PR TITLE
Add `image/heic` mime type

### PR DESCRIPTION
**Pull request by aliasgarlabs**
Adding `heic` extension with mime type `image/heic`.

### CODE REVIEW

**Comment by aliasgarlabs** [comment]
I signed it!

**Review by krasznaidavid — APPROVED** [review]

**Comment by kevmoo** [comment]
should have a changelog entry and a test!

**Comment by kevmoo** [comment]
@natebosch – should we do a "dot" release `1.1` – since we are adding features?

**Comment by natebosch** [comment]
> @natebosch – should we do a "dot" release `1.1` – since we are adding features?

Since 1.0 we've done patch releases for adding mime types. I think you could make a good argument either way, but my inclination is to stick with that pattern.

**Review by natebosch — APPROVED** [review]

**Pull request merged**
