### PR TITLE
Adds support for glTF - text and binary formats

### PR DESCRIPTION
**Pull request by mfrancis107**
See: https://github.com/KhronosGroup/glTF

### CODE REVIEW

**Comment by mfrancis107** [comment]
Update

**Comment by kevmoo** [comment]
@nex3 – you might have to do the merge...

**Comment by kevmoo** [comment]
Also: in the pubspec in order, etc?

**Comment by nex3** [comment]
Isn't this still waiting on @mkustermann's review?

For my packages, I usually do the pubspec/changelog/etc myself for third-party pull requests when I land... but this isn't really something I maintain.

**Comment by mkustermann** [comment]
Seems like `model/gltf+json` made it into [iana.org/.../model/gltf+json](https://www.iana.org/assignments/media-types/model/gltf+json) though I cannot find `model/gltf-binary` there (it seemed a bit odd that one is using a `+` and the other one is using a `-`).

Though at [other places](https://github.com/AnalyticalGraphicsInc/cesium/pull/5420/files#diff-78c12f5adc1848d13b1c6f07055d996e) the same was added.

So it looks good to me!

**Pull request merged**
