### PR TITLE
change the mime type for dart source

### PR DESCRIPTION
**Pull request by devoncarew**
Change the mime type for Dart source from `application/dart` to `text/x-dart`.

When working on a server serving up a browser based directory listing, I noticed that Dart source files were not displayed by the browser, but instead popped up a dialog asking to save them as binary content. Other source files (css, html, ...) were instead displayed in the browser.

The server was reporting `application/dart` as the mime type for Dart files. The `application/` prefix is an indication to the browser that the file has binary content; as the browser didn't understand that binary format, it didn't attempt to display it.

Previously we had native processors of Dart files (and the `application/dart` mime type) - Dartium; however executable Dart on the web now just exists in the form of compiled JS files.

I think we should change the default mime type of Dart files to something that browsers will recognize as text based. From a quick perusal of other languages (and reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types), this would be something like `text/x-dart`.

@kevmoo @anders-sandholm

### CODE REVIEW

**Comment by anders-sandholm** [comment]
Generally SGTM.
What are potential negative implications from changing this?
In what other places should or would we need to change this as well, if any?

**Comment by kevmoo** [comment]
Thoughts @nex3 @natebosch @jakemac53 ?

Devon: what scenario are you working on here? Just curious...

**Comment by natebosch** [comment]
This seems sensible to me. @vsmenon any concerns around source maps or anything?

**Comment by devoncarew** [comment]
> Devon: what scenario are you working on here? Just curious...

I was working on a server that served file listings for directories (and file contents for files - based on https://github.com/dart-lang/shelf_static. I noticed that the dart source files were the only file type that couldn't be displayed. Given that they're just straight text files, it was odd and a bit inconvenient. It's not really a deal breaker type of thing, but likely inconsistent with where we should be, given the current dart4web support (dart2js+DDC, rather than Dartium).

> What are potential negative implications from changing this?

Good question! I don't know of any, but worth gathering thoughts here.

> In what other places should or would we need to change this as well, if any?

I found references here:
- https://webdev.dartlang.org/articles/low-level-html/embedding-in-html ("Content on this page is obsolete.")
- https://webdev.dartlang.org/tools/dartium

And there are likely others.

And in terms of other language mime types, I found: `text/x-rust`, `text/x-rustsrc` (http://codemirror.net/mode/rust/), `text/x-go`, `text/x-swift`, but did not do more than casual browsing.

**Comment by jakemac53** [comment]
Sounds good to me, do we need to treat this as a breaking change?

**Comment by vsmenon** [comment]
Moving away from `application/dart` SGTM.  That was purely a Dartium need back in the day.

Does the pubspec already imply that this package will not work with Dartium?

**Comment by natebosch** [comment]
@vsmenon - the min SDK is `2.0.0-dev.20.0` which is past when we supported Dartium so I think this is relatively safe.

Technically this could be used on a server which still has a Dartium client, but I think the risk there is low.

**Pull request merged**
